### ISSUE TITLE
on clicking on menu buttons new window opens

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/spotify-downloader-music-player#33]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request

**Actual Behaviour**

always new GUI opens when click on buttons

**Expected Behaviour**

old GUI should be close when new GUI opens

**Steps to reproduce it**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

**Comment by AbhiY98** [comment]
Hey, I would like to work on this issue.
Could you please assign it to me.

**Comment by rpotter12** [comment]
@AbhiY98 In assignees list your name is visible maybe because you haven't fork repo yet. You can start working on this issue. I will assign this issue when you generate a PR :)

**Comment by rpotter12** [comment]
@AbhiY98 are you working on this issue??

**Comment by AbhiY98** [comment]
@rpotter12  Yes.
I will try to create a PR As soon as possible.
